version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: guestbook
      POSTGRES_PASSWORD: guestbook
      POSTGRES_DB: guestbook
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: