// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"net"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Guest struct {
	ID        uuid.UUID
	Message   string
	Ip        net.IP
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OptionChain struct {
	ID          uuid.UUID
	Symbol      string
	SpotPrice   string
	ExpiryDate  pgtype.Date
	ExpiryType  string
	OptionChain []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type OptionExpiry struct {
	ID          uuid.UUID
	Symbol      string
	ExpiryDate  pgtype.Date
	ExpiryType  string
	OptionChain []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type OptionExpiryDate struct {
	ID          uuid.UUID
	Symbol      string
	ExpiryDates []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
