// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"
	"net"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const count = `-- name: Count :one
SELECT COUNT(*) FROM guest
`

func (q *Queries) Count(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, count)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findAll = `-- name: FindAll :many
SELECT id, message, ip, created_at, updated_at
FROM guest
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) FindAll(ctx context.Context, limit int32) ([]Guest, error) {
	rows, err := q.db.Query(ctx, findAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guest
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.Ip,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGEXChangeForSymbols = `-- name: GetGEXChangeForSymbols :many
WITH latest AS (
    SELECT DISTINCT ON (symbol)
        symbol,
        gex_value as current_gex,
        spot_price as current_price,
        expiry_date,
        recorded_at as current_time
    FROM gex_history
    WHERE gex_history.recorded_at >= $1
    ORDER BY symbol, expiry_date ASC, gex_history.recorded_at DESC
),
previous AS (
    SELECT DISTINCT ON (symbol)
        symbol,
        gex_value as previous_gex,
        recorded_at as previous_time
    FROM gex_history
    WHERE gex_history.recorded_at >= $2 AND gex_history.recorded_at < $1
    ORDER BY symbol, expiry_date ASC, gex_history.recorded_at DESC
)
SELECT
    l.symbol,
    l.current_gex,
    l.current_price,
    l.expiry_date,
    l.current_time,
    COALESCE(p.previous_gex, 0) as previous_gex,
    p.previous_time,
    (l.current_gex - COALESCE(p.previous_gex, 0))::numeric as gex_change,
    (CASE
        WHEN COALESCE(p.previous_gex, 0) != 0
        THEN ((l.current_gex - COALESCE(p.previous_gex, 0)) / ABS(p.previous_gex)) * 100
        ELSE 0
    END)::numeric as gex_change_pct
FROM latest l
LEFT JOIN previous p ON l.symbol = p.symbol
ORDER BY ABS(l.current_gex - COALESCE(p.previous_gex, 0)) DESC
`

type GetGEXChangeForSymbolsParams struct {
	RecordedAt   time.Time
	RecordedAt_2 time.Time
}

type GetGEXChangeForSymbolsRow struct {
	Symbol       string
	CurrentGex   pgtype.Numeric
	CurrentPrice pgtype.Text
	ExpiryDate   pgtype.Date
	CurrentTime  time.Time
	PreviousGex  pgtype.Numeric
	PreviousTime pgtype.Timestamptz
	GexChange    pgtype.Numeric
	GexChangePct pgtype.Numeric
}

func (q *Queries) GetGEXChangeForSymbols(ctx context.Context, arg GetGEXChangeForSymbolsParams) ([]GetGEXChangeForSymbolsRow, error) {
	rows, err := q.db.Query(ctx, getGEXChangeForSymbols, arg.RecordedAt, arg.RecordedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGEXChangeForSymbolsRow
	for rows.Next() {
		var i GetGEXChangeForSymbolsRow
		if err := rows.Scan(
			&i.Symbol,
			&i.CurrentGex,
			&i.CurrentPrice,
			&i.ExpiryDate,
			&i.CurrentTime,
			&i.PreviousGex,
			&i.PreviousTime,
			&i.GexChange,
			&i.GexChangePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGexHistoryBySymbolAndExpiry = `-- name: GetGexHistoryBySymbolAndExpiry :many
SELECT id, symbol, expiry_date, expiry_type, option_chain, gex_value, recorded_at, spot_price FROM gex_history
WHERE symbol = $1 AND expiry_date = $2
ORDER BY recorded_at DESC
    LIMIT $3
`

type GetGexHistoryBySymbolAndExpiryParams struct {
	Symbol     string
	ExpiryDate pgtype.Date
	Limit      int32
}

func (q *Queries) GetGexHistoryBySymbolAndExpiry(ctx context.Context, arg GetGexHistoryBySymbolAndExpiryParams) ([]GexHistory, error) {
	rows, err := q.db.Query(ctx, getGexHistoryBySymbolAndExpiry, arg.Symbol, arg.ExpiryDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GexHistory
	for rows.Next() {
		var i GexHistory
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.ExpiryDate,
			&i.ExpiryType,
			&i.OptionChain,
			&i.GexValue,
			&i.RecordedAt,
			&i.SpotPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestGEXChanges = `-- name: GetLatestGEXChanges :many
WITH ranked_history AS (
    SELECT
        symbol,
        gex_value,
        spot_price,
        expiry_date,
        recorded_at,
        ROW_NUMBER() OVER (PARTITION BY symbol ORDER BY recorded_at DESC) as rn
    FROM gex_history
),
latest AS (
    SELECT
        symbol,
        gex_value as current_gex,
        spot_price as current_price,
        expiry_date,
        recorded_at as current_time
    FROM ranked_history
    WHERE rn = 1
),
previous AS (
    SELECT
        symbol,
        gex_value as previous_gex,
        recorded_at as previous_time
    FROM ranked_history
    WHERE rn = 2
)
SELECT
    l.symbol,
    l.current_gex,
    l.current_price,
    l.expiry_date,
    l.current_time,
    COALESCE(p.previous_gex, 0) as previous_gex,
    p.previous_time,
    (l.current_gex - COALESCE(p.previous_gex, 0))::numeric as gex_change,
    (CASE
        WHEN COALESCE(p.previous_gex, 0) != 0
        THEN ((l.current_gex - COALESCE(p.previous_gex, 0)) / ABS(p.previous_gex)) * 100
        ELSE 0
    END)::numeric as gex_change_pct
FROM latest l
LEFT JOIN previous p ON l.symbol = p.symbol
ORDER BY ABS(l.current_gex - COALESCE(p.previous_gex, 0)) DESC
`

type GetLatestGEXChangesRow struct {
	Symbol       string
	CurrentGex   pgtype.Numeric
	CurrentPrice pgtype.Text
	ExpiryDate   pgtype.Date
	CurrentTime  time.Time
	PreviousGex  pgtype.Numeric
	PreviousTime pgtype.Timestamptz
	GexChange    pgtype.Numeric
	GexChangePct pgtype.Numeric
}

func (q *Queries) GetLatestGEXChanges(ctx context.Context) ([]GetLatestGEXChangesRow, error) {
	rows, err := q.db.Query(ctx, getLatestGEXChanges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestGEXChangesRow
	for rows.Next() {
		var i GetLatestGEXChangesRow
		if err := rows.Scan(
			&i.Symbol,
			&i.CurrentGex,
			&i.CurrentPrice,
			&i.ExpiryDate,
			&i.CurrentTime,
			&i.PreviousGex,
			&i.PreviousTime,
			&i.GexChange,
			&i.GexChangePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestGEXHistoryBySymbol = `-- name: GetLatestGEXHistoryBySymbol :many
SELECT id, symbol, expiry_date, recorded_at, gex_value, option_chain, spot_price
FROM gex_history
WHERE symbol = $1 AND recorded_at >= $2
ORDER BY recorded_at DESC
    LIMIT $3
`

type GetLatestGEXHistoryBySymbolParams struct {
	Symbol     string
	RecordedAt time.Time
	Limit      int32
}

type GetLatestGEXHistoryBySymbolRow struct {
	ID          uuid.UUID
	Symbol      string
	ExpiryDate  pgtype.Date
	RecordedAt  time.Time
	GexValue    pgtype.Numeric
	OptionChain []byte
	SpotPrice   pgtype.Text
}

func (q *Queries) GetLatestGEXHistoryBySymbol(ctx context.Context, arg GetLatestGEXHistoryBySymbolParams) ([]GetLatestGEXHistoryBySymbolRow, error) {
	rows, err := q.db.Query(ctx, getLatestGEXHistoryBySymbol, arg.Symbol, arg.RecordedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestGEXHistoryBySymbolRow
	for rows.Next() {
		var i GetLatestGEXHistoryBySymbolRow
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.ExpiryDate,
			&i.RecordedAt,
			&i.GexValue,
			&i.OptionChain,
			&i.SpotPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOptionChainBySymbolAndExpiry = `-- name: GetOptionChainBySymbolAndExpiry :one
SELECT id, symbol, spot_price, expiry_date, expiry_type, option_chain, created_at, updated_at FROM option_chain
WHERE symbol = $1 and expiry_date = $2
`

type GetOptionChainBySymbolAndExpiryParams struct {
	Symbol     string
	ExpiryDate pgtype.Date
}

func (q *Queries) GetOptionChainBySymbolAndExpiry(ctx context.Context, arg GetOptionChainBySymbolAndExpiryParams) (OptionChain, error) {
	row := q.db.QueryRow(ctx, getOptionChainBySymbolAndExpiry, arg.Symbol, arg.ExpiryDate)
	var i OptionChain
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.SpotPrice,
		&i.ExpiryDate,
		&i.ExpiryType,
		&i.OptionChain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOptionExpiryBySymbolAndExpiry = `-- name: GetOptionExpiryBySymbolAndExpiry :many
SELECT id, symbol, expiry_date, expiry_type, option_chain, created_at, updated_at FROM option_expiry
WHERE symbol = $1 AND expiry_date = $2
ORDER BY expiry_date ASC
`

type GetOptionExpiryBySymbolAndExpiryParams struct {
	Symbol     string
	ExpiryDate pgtype.Date
}

func (q *Queries) GetOptionExpiryBySymbolAndExpiry(ctx context.Context, arg GetOptionExpiryBySymbolAndExpiryParams) ([]OptionExpiry, error) {
	rows, err := q.db.Query(ctx, getOptionExpiryBySymbolAndExpiry, arg.Symbol, arg.ExpiryDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OptionExpiry
	for rows.Next() {
		var i OptionExpiry
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.ExpiryDate,
			&i.ExpiryType,
			&i.OptionChain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOptionExpiryDatesBySymbol = `-- name: GetOptionExpiryDatesBySymbol :one
SELECT id, symbol, expiry_dates, created_at, updated_at FROM option_expiry_dates
WHERE symbol = $1
`

func (q *Queries) GetOptionExpiryDatesBySymbol(ctx context.Context, symbol string) (OptionExpiryDate, error) {
	row := q.db.QueryRow(ctx, getOptionExpiryDatesBySymbol, symbol)
	var i OptionExpiryDate
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.ExpiryDates,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThisWeekReleases = `-- name: GetThisWeekReleases :many
SELECT id, release_id, release_name, release_date, impact, created_at, updated_at FROM economic_releases
WHERE release_date >= CURRENT_DATE - 7 AND release_date <= CURRENT_DATE + 7
ORDER BY release_date DESC, impact DESC
`

func (q *Queries) GetThisWeekReleases(ctx context.Context) ([]EconomicRelease, error) {
	rows, err := q.db.Query(ctx, getThisWeekReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EconomicRelease
	for rows.Next() {
		var i EconomicRelease
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.ReleaseName,
			&i.ReleaseDate,
			&i.Impact,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingReleases = `-- name: GetUpcomingReleases :many
SELECT id, release_id, release_name, release_date, impact, created_at, updated_at FROM economic_releases
WHERE release_date >= $1 AND release_date <= $2
ORDER BY release_date ASC, impact DESC
`

type GetUpcomingReleasesParams struct {
	ReleaseDate   pgtype.Date
	ReleaseDate_2 pgtype.Date
}

func (q *Queries) GetUpcomingReleases(ctx context.Context, arg GetUpcomingReleasesParams) ([]EconomicRelease, error) {
	rows, err := q.db.Query(ctx, getUpcomingReleases, arg.ReleaseDate, arg.ReleaseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EconomicRelease
	for rows.Next() {
		var i EconomicRelease
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.ReleaseName,
			&i.ReleaseDate,
			&i.Impact,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insert = `-- name: Insert :one
INSERT INTO guest (id, message, created_at, updated_at, ip)
VALUES ($1, $2, $3, $3, $4)
RETURNING id, message, ip, created_at, updated_at
`

type InsertParams struct {
	ID        uuid.UUID
	Message   string
	CreatedAt time.Time
	Ip        net.IP
}

func (q *Queries) Insert(ctx context.Context, arg InsertParams) (Guest, error) {
	row := q.db.QueryRow(ctx, insert,
		arg.ID,
		arg.Message,
		arg.CreatedAt,
		arg.Ip,
	)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.Ip,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGEXHistory = `-- name: InsertGEXHistory :one
INSERT INTO gex_history (
    id, symbol, expiry_date, expiry_type, option_chain, gex_value, recorded_at, spot_price
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    RETURNING id, symbol, expiry_date, expiry_type, option_chain, gex_value, recorded_at, spot_price
`

type InsertGEXHistoryParams struct {
	ID          uuid.UUID
	Symbol      string
	ExpiryDate  pgtype.Date
	ExpiryType  string
	OptionChain []byte
	GexValue    pgtype.Numeric
	RecordedAt  time.Time
	SpotPrice   pgtype.Text
}

func (q *Queries) InsertGEXHistory(ctx context.Context, arg InsertGEXHistoryParams) (GexHistory, error) {
	row := q.db.QueryRow(ctx, insertGEXHistory,
		arg.ID,
		arg.Symbol,
		arg.ExpiryDate,
		arg.ExpiryType,
		arg.OptionChain,
		arg.GexValue,
		arg.RecordedAt,
		arg.SpotPrice,
	)
	var i GexHistory
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.ExpiryDate,
		&i.ExpiryType,
		&i.OptionChain,
		&i.GexValue,
		&i.RecordedAt,
		&i.SpotPrice,
	)
	return i, err
}

const upsertEconomicRelease = `-- name: UpsertEconomicRelease :one
INSERT INTO economic_releases (release_id, release_name, release_date, impact)
VALUES ($1, $2, $3, $4)
ON CONFLICT (release_id, release_date)
DO UPDATE SET
    release_name = EXCLUDED.release_name,
    impact = EXCLUDED.impact,
    updated_at = now()
RETURNING id, release_id, release_name, release_date, impact, created_at, updated_at
`

type UpsertEconomicReleaseParams struct {
	ReleaseID   int32
	ReleaseName string
	ReleaseDate pgtype.Date
	Impact      string
}

// Economic Releases (FRED API)
func (q *Queries) UpsertEconomicRelease(ctx context.Context, arg UpsertEconomicReleaseParams) (EconomicRelease, error) {
	row := q.db.QueryRow(ctx, upsertEconomicRelease,
		arg.ReleaseID,
		arg.ReleaseName,
		arg.ReleaseDate,
		arg.Impact,
	)
	var i EconomicRelease
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ReleaseName,
		&i.ReleaseDate,
		&i.Impact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOptionChain = `-- name: UpsertOptionChain :one
INSERT INTO option_chain (
    symbol,
    spot_price,
    expiry_date,
    expiry_type,
    option_chain
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (symbol, expiry_date)
DO UPDATE SET
    spot_price = EXCLUDED.spot_price,
    option_chain = EXCLUDED.option_chain,
    updated_at = now()
RETURNING id, symbol, spot_price, expiry_date, expiry_type, option_chain, created_at, updated_at
`

type UpsertOptionChainParams struct {
	Symbol      string
	SpotPrice   string
	ExpiryDate  pgtype.Date
	ExpiryType  string
	OptionChain []byte
}

func (q *Queries) UpsertOptionChain(ctx context.Context, arg UpsertOptionChainParams) (OptionChain, error) {
	row := q.db.QueryRow(ctx, upsertOptionChain,
		arg.Symbol,
		arg.SpotPrice,
		arg.ExpiryDate,
		arg.ExpiryType,
		arg.OptionChain,
	)
	var i OptionChain
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.SpotPrice,
		&i.ExpiryDate,
		&i.ExpiryType,
		&i.OptionChain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOptionExpiry = `-- name: UpsertOptionExpiry :one
INSERT INTO option_expiry (
    symbol,
    expiry_date,
    expiry_type,
    option_chain
) VALUES ($1, $2, $3, $4)
ON CONFLICT (symbol, expiry_date)
DO UPDATE SET
    option_chain = EXCLUDED.option_chain,
    updated_at = now()
RETURNING id, symbol, expiry_date, expiry_type, option_chain, created_at, updated_at
`

type UpsertOptionExpiryParams struct {
	Symbol      string
	ExpiryDate  pgtype.Date
	ExpiryType  string
	OptionChain []byte
}

func (q *Queries) UpsertOptionExpiry(ctx context.Context, arg UpsertOptionExpiryParams) (OptionExpiry, error) {
	row := q.db.QueryRow(ctx, upsertOptionExpiry,
		arg.Symbol,
		arg.ExpiryDate,
		arg.ExpiryType,
		arg.OptionChain,
	)
	var i OptionExpiry
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.ExpiryDate,
		&i.ExpiryType,
		&i.OptionChain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOptionExpiryDates = `-- name: UpsertOptionExpiryDates :one
INSERT INTO option_expiry_dates (
    symbol,
    expiry_dates
) VALUES ($1, $2)
ON CONFLICT (symbol)
    DO UPDATE SET
                  expiry_dates = EXCLUDED.expiry_dates,
                  updated_at = now()
RETURNING id, symbol, expiry_dates, created_at, updated_at
`

type UpsertOptionExpiryDatesParams struct {
	Symbol      string
	ExpiryDates []byte
}

func (q *Queries) UpsertOptionExpiryDates(ctx context.Context, arg UpsertOptionExpiryDatesParams) (OptionExpiryDate, error) {
	row := q.db.QueryRow(ctx, upsertOptionExpiryDates, arg.Symbol, arg.ExpiryDates)
	var i OptionExpiryDate
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.ExpiryDates,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
